/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Difficulty = IDL.Variant({ 'easy' : IDL.Null, 'hard' : IDL.Null });
export const Time = IDL.Int;
export const T = IDL.Record({
  'player' : IDL.Principal,
  'difficulty' : Difficulty,
  'score' : IDL.Nat,
  'timestamp' : Time,
});
export const PlayerStats = IDL.Record({
  'bestScore' : IDL.Nat,
  'runsPlayed' : IDL.Nat,
});
export const DailyChallengeSeed = IDL.Text;
export const PlayerProfile = IDL.Record({
  'displayName' : IDL.Text,
  'stats' : PlayerStats,
  'lastDailyChallenge' : IDL.Tuple(Time, DailyChallengeSeed),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllHighScores' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyChallenge' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DailyChallengeSeed)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'startDailyChallenge' : IDL.Func([DailyChallengeSeed], [], []),
  'submitScore' : IDL.Func([IDL.Nat, Difficulty], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Difficulty = IDL.Variant({ 'easy' : IDL.Null, 'hard' : IDL.Null });
  const Time = IDL.Int;
  const T = IDL.Record({
    'player' : IDL.Principal,
    'difficulty' : Difficulty,
    'score' : IDL.Nat,
    'timestamp' : Time,
  });
  const PlayerStats = IDL.Record({
    'bestScore' : IDL.Nat,
    'runsPlayed' : IDL.Nat,
  });
  const DailyChallengeSeed = IDL.Text;
  const PlayerProfile = IDL.Record({
    'displayName' : IDL.Text,
    'stats' : PlayerStats,
    'lastDailyChallenge' : IDL.Tuple(Time, DailyChallengeSeed),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllHighScores' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyChallenge' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DailyChallengeSeed)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'startDailyChallenge' : IDL.Func([DailyChallengeSeed], [], []),
    'submitScore' : IDL.Func([IDL.Nat, Difficulty], [], []),
  });
};

export const init = ({ IDL }) => { return []; };