/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DailyChallengeSeed = string;
export type Difficulty = { 'easy' : null } |
  { 'hard' : null };
export interface PlayerProfile {
  'displayName' : string,
  'stats' : PlayerStats,
  'lastDailyChallenge' : [Time, DailyChallengeSeed],
}
export interface PlayerStats { 'bestScore' : bigint, 'runsPlayed' : bigint }
export interface T {
  'player' : Principal,
  'difficulty' : Difficulty,
  'score' : bigint,
  'timestamp' : Time,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllHighScores' : ActorMethod<[], Array<T>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PlayerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyChallenge' : ActorMethod<[string], [] | [DailyChallengeSeed]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PlayerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'startDailyChallenge' : ActorMethod<[DailyChallengeSeed], undefined>,
  'submitScore' : ActorMethod<[bigint, Difficulty], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];